#ifndef STYLEDEFINE_H
#define STYLEDEFINE_H

//编辑器默认配置
#define EDITOR_DEFAULT_FONTFAMILIES_FIRST "Microsoft YaHei"
#define EDITOR_DEFAULT_FONTFAMILIES_SECOND "Calibri(Body)"
#define EDITOR_DEFAULT_FONT_SIZE quint16(16)
#define EDITOR_DEFAULT_FONT_WEIGHT quint16(200)
#define EDITOR_DEFAULT_FONT_LINE_HEIGHT double(1.2)
#define EDITOR_DEFAULT_IS_LIGHT_STYLE true

#define STYLEKEY_FONT_FAMILIES "@fontFamilies"
#define STYLEKEY_FONT_SIZE "@fontSize"
#define STYLEKEY_FONT_WEIGHT "@fontWeight"

#endif // STYLEDEFINE_H
