#ifndef CONFIGDEFINE_H
#define CONFIGDEFINE_H

#define CONFIG_SYSTEM_PATH "./res/config"

#define CONFIG_SYSTEM_FILENAME "system.json"

//系统配置
#define CONFIG_SYSTEM_APPLICATION_NAME "NovelMaker"
#define CONFIG_SYSTEM_APPLICATION_DISPLAYNAME "小说编辑器"
#define CONFIG_SYSTEM_APPLICATION_VERSION "0.0.1"
#define CONFIG_SYSTEM_APPLICATION_BUILDNUMBER 000001
#define CONFIG_SYSTEM_APPLICATION_EDITOR "lidada"
#define CONFIG_SYSTEM_APPLICATION_WEBSITE "https://github.com/LIDADAEX/NovelMaker"

#endif // CONFIGDEFINE_H
